apiVersion: apps/v1
kind: Deployment
metadata:
    name: vue
spec:
    selector:
        matchLabels:
            app: vue
    replicas: 2
    template:
        metadata:
            labels:
                app: vue
        spec:
            containers:
                - name: vue-container
                  image: ajrohrer/recipevue:v1.1
                  ports:
                  - containerPort: 80
kind: Service
apiVersion: v1
metadata:
    name: recipe-service
spec:
    selector:
        app: vue
    ports:
    - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
    type: NodePort