apiVersion: apps/v1
kind: Deployment
metadata:
    name: vue
spec:
    selector:
        matchLabels:
            app: vue
    replicas: 2
    template:
        metadata:
            labels:
                app: vue
        spec:
            containers:
                - name: vue-container
                  image: ajrohrer/recipevue:v1.3
                  ports:
                  - containerPort: 80