apiVersion: v1
kind: Service
metadata:
    name: recipe-vue
spec:
    selector:
        app: vue
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
    type: NodePort